
DROP TABLE foo;

CREATE TABLE foo (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  date_created TIMESTAMP NOT NULL,
  item_name VARCHAR(1024) NOT NULL,
  PRIMARY KEY(id)
);

INSERT INTO foo (date_created, item_name) VALUES ('2016-01-01 00:00:00', 'First item');
INSERT INTO foo (date_created, item_name) VALUES ('2016-01-02 00:00:00', 'Second item');
INSERT INTO foo (date_created, item_name) VALUES ('2016-01-03 00:00:00', 'Third item');
