name: Lint

on:
    schedule:
        - cron: "30 0 * * *"
    push:
        branches:
            - master
    pull_request:

permissions:
    contents: read

jobs:
    composer:
        name: Composer

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: "actions/checkout@v3"

            - name: "Install PHP with extensions"
              uses: "shivammathur/setup-php@v2"
              with:
                  php-version: "8.2"
                  coverage: none
                  tools: "composer:v2, composer-normalize:2"
              env:
                  COMPOSER_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

            - name: "Lint Composer"
              run: |
                  composer-normalize --dry-run
                  composer validate
