name: "Build"
on:
    push:
        branches:
            - master
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-version: ["7.1", "8.2"]
                dependencies: ["highest", "lowest"]

        steps:
            - name: "Checkout"
              uses: "actions/checkout@v3"
              with:
                  fetch-depth: 2

            - name: "Install IBM i Access ODBC driver"
              working-directory: /tmp
              run: |
                  curl "https://public.dhe.ibm.com/software/ibmi/products/odbc/debs/dists/1.1.0/ibmi-acs-1.1.0.list" | sudo tee /etc/apt/sources.list.d/ibmi-acs-1.1.0.list
                  sudo apt-get update
                  sudo apt-get install -qq --yes --no-install-recommends ibm-iaccess

            - name: "Install IBM CLI driver"
              working-directory: /tmp
              run: |
                  wget "https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz"
                  tar xf linuxx64_odbc_cli.tar.gz
                  rm linuxx64_odbc_cli.tar.gz

            - name: "Determine version for ibm_db2"
              id: ibm_db2_ver
              run: |
                  if [[ "${{ matrix.php-version }}" == 7.1* ]] || [[ "${{ matrix.php-version }}" == 7.2* ]]; then
                      echo "ibm_db2_ver=2.1.3" >> "$GITHUB_OUTPUT"
                  else
                      echo "ibm_db2_ver=2.1.7" >> "$GITHUB_OUTPUT"
                  fi;

            - name: "Install PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                  php-version: "${{ matrix.php-version }}"
                  extensions: "pdo_odbc, ibm_db2-${{ steps.ibm_db2_ver.outputs.ibm_db2_ver }}"
                  coverage: "pcov"
                  ini-values: "zend.assertions=1, ibm_db2.instance_name=db2inst1"
              env:
                  PDO_ODBC_CONFIGURE_OPTS: "--with-pdo-odbc=unixODBC,/usr"
                  IBM_DB2_CONFIGURE_OPTS: "--with-IBM_DB2=/tmp/clidriver"

            - name: "Install dependencies with Composer (${{ matrix.dependencies }})"
              uses: "ramsey/composer-install@v2"
              with:
                  dependency-versions: "${{ matrix.dependencies }}"
